- apt_repository:
    repo: 'ppa:certbot/certbot'

- name: apt-get update
  apt:
    upgrade: dist
    update_cache: yes

- name: install apt packages
  apt:
    name: ['nginx', 'letsencrypt']
    state: latest