- name: install apt packages
  apt: name={{ item }} state=latest # update_cache=yes cache_valid_time=3600
  with_items:
   - emacs24-nox
   # ---docker---
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common
   # ---end docker---
